
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./_components/header";
import Providers from "./_app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark w-full h-100">
      <body>
        <Providers>
          <Header />
          <div className="xl:container flex flex-row justify-center">
            <div>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
