import '@mantine/core/styles/global.css';
import '@mantine/core/styles/ColorPicker.css';
import '@mantine/core/styles/ColorSwatch.css';
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./_root_layout/components/header";
import Providers from "./_session-provider";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { deleteUser } from './_root_layout/actions/delete-account';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark w-full h-full">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Providers>
            <Header deleteUser={deleteUser} />
            <div className="xl:container flex flex-row justify-center p-4">
              <div className="w-full">{children}</div>
            </div>
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
